import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-dark": "#0d0d0d",
        "bg-section": "#171717",
        "bg-elevated": "#1f1f1f",
        "text-primary": "#fafafa",
        "text-secondary": "#a3a3a3",
        "text-tertiary": "#737373",
        "text-inverse": "#0a0a0a",
        accent: "#ff6b6b",
        "accent-subtle": "#ff8787",
        overlay: "rgba(0,0,0,0.85)",
        smoke: {
          50: "#fef2f2",
          100: "#fde8e8",
          200: "#fbd5d5",
          300: "#f8b4b4",
          400: "#f98080",
          500: "#f05252",
          600: "#e02424",
          700: "#c81e1e",
          800: "#9b1c1c",
          900: "#771d1d",
        },
        era: {
          "50s": "#d4a574",
          "70s": "#e8a23d",
          "80s": "#dd5e89",
          "90s": "#4ecdc4",
          "00s": "#95a5a6",
          "10s": "#667eea",
        },
        glass: "rgba(255, 255, 255, 0.05)",
        "glass-border": "rgba(255, 255, 255, 0.1)",
      },
      fontFamily: {
        sans: ["Inter Variable", "Inter", "system-ui", "sans-serif"],
        display: ["Crimson Pro", "Georgia", "serif"],
        mono: ["JetBrains Mono", "Courier New", "monospace"],
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em" }],
        sm: ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em" }],
        base: ["1rem", { lineHeight: "1.5rem", letterSpacing: "0" }],
        lg: ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em" }],
        xl: ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em" }],
        "2xl": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em" }],
        "3xl": ["2rem", { lineHeight: "2.25rem", letterSpacing: "-0.03em" }],
        "4xl": ["2.5rem", { lineHeight: "2.75rem", letterSpacing: "-0.04em" }],
        "5xl": ["3.5rem", { lineHeight: "3.75rem", letterSpacing: "-0.05em" }],
        "6xl": ["4.5rem", { lineHeight: "4.75rem", letterSpacing: "-0.06em" }],
        "7xl": ["6rem", { lineHeight: "6.25rem", letterSpacing: "-0.07em" }],
      },
      lineHeight: {
        tight: "1.1",
        snug: "1.2",
        normal: "1.5",
        relaxed: "1.75",
      },
      spacing: {
        xs: "0.5rem",
        sm: "1rem",
        md: "2rem",
        lg: "4rem",
        xl: "6rem",
        "2xl": "8rem",
      },
      maxWidth: {
        container: "1400px",
        "container-narrow": "800px",
        "container-wide": "1800px",
      },
      transitionTimingFunction: {
        "in-expo": "cubic-bezier(0.95, 0.05, 0.795, 0.035)",
        "out-expo": "cubic-bezier(0.19, 1, 0.22, 1)",
        "in-out-expo": "cubic-bezier(1, 0, 0, 1)",
        spring: "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        pudding: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      animation: {
        "fade-in": "fadeIn 0.8s ease-out forwards",
        "fade-in-up": "fadeInUp 1s ease-out forwards",
        "scale-in": "scaleIn 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55) forwards",
        "slide-up": "slideUp 0.8s cubic-bezier(0.19, 1, 0.22, 1) forwards",
        "slide-down": "slideDown 2s ease-in-out infinite",
        "text-shimmer": "shimmer 3s ease-in-out infinite",
        grain: "grain 8s steps(10) infinite",
        float: "float 6s ease-in-out infinite",
        pulse: "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideUp: {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
        slideDown: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(100%)" },
        },
        shimmer: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        grain: {
          "0%, 100%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(-5%, -5%)" },
          "30%": { transform: "translate(3%, -8%)" },
          "50%": { transform: "translate(12%, 9%)" },
          "70%": { transform: "translate(-9%, 4%)" },
          "90%": { transform: "translate(-1%, -7%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px) translateX(0px)" },
          "50%": { transform: "translateY(-20px) translateX(10px)" },
        },
      },
      screens: {
        xs: "375px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
        "3xl": "1920px",
      },
      zIndex: {
        background: "-1",
        content: "1",
        overlay: "10",
        modal: "100",
        toast: "1000",
      },
    },
  },
  plugins: [],
};

export default config;
